#!/usr/bin/env node
const { Artist, Genre, Album, Upcoming_show, db } = require('../models');
const { artists, genres, albums, upcoming_shows } = require('../data');


(async () => {

  // first insert the artists
  await Artist.bulkCreate(artists.map(([name, desc, img_url]) => ({ name, desc, img_url})));
//bulk create expects an array of objects that have keys
//this function takes the array [name,img_url] and makes it an object
//this is a sequelize method

  // then insert the genres
  await Genre.bulkCreate(genres.map(([name]) => ({name})));

  await Album.bulkCreate(albums.map(([name, img_url, artist_id]) => ({name, img_url, artist_id})));

await Upcoming_show.bulkCreate(upcoming_shows.map(([date, venue]) => ({date, venue})));

  db.close();
})();
